Report: Adding first pass of built in vocab check
ontodev/robot pull request #867
Opened 2021-05-16 15:54 UTC by matentzn

Resolves #835 

- [X] `docs/` have been added/updated
- [ ] tests have been added/updated
- [ ] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [ ] `CHANGELOG.md` has been updated

Adding a first check to prevent use of rdf:type in an axiom as a subject. Its less than what we wanted, but maybe lets just build the check up slowly slowly.

2021-05-17 14:34 UTC, beckyjackson requested changes
Query looks good and this is definitely a needed check in my opinion.

2021-05-17 14:34 UTC, beckyjackson commented on docs/report_queries/illegal_use_of_built_in_vocabulary.md
> +# Illegal annotation of built-in vocabulary
This should match the file name:

> Illegal Use of Built-In Vocabulary

2021-05-17 14:34 UTC, beckyjackson commented on robot-core/src/main/resources/report_profile.txt
> +ERROR	illegal_use_of_built_in_vocabulary
Please put in alphabetical order

2021-05-17 19:56 UTC, matentzn commented
@beckyjackson thanks! PR updated!

2021-06-02 14:13 UTC, beckyjackson commented
Everything looks good. Are there any other builtins we want to include before merging this? Maybe `rdfs:subClassOf`, etc?

2021-06-02 14:13 UTC, beckyjackson approved these changes
Looks good. I also want @jamesaoverton to take a look before merging.

2021-09-21 16:17 UTC, merged