884 fix patch
ontodev/robot pull request #889
Opened 2021-07-18 15:02 UTC by matentzn

Two suggestions @beckyjackson :

1) We should ignore `some-obsolete subclassOf Thing.` this error is so frequent, it will totally pollute the test.
2) In an attempt to reduce spurious diffs over ROBOT report (see https://github.com/ontodev/robot/issues/873) I would suggest to avoid blank nodes in robot report.

2021-07-18 15:08 UTC, matentzn commented
Something is wrong wait a moment..

2021-07-18 15:28 UTC, matentzn commented
Ok now

2021-07-18 20:59 UTC, beckyjackson commented
I think "Use in anonymous expression" should be rephrased as just "anonymous expression", since that's the entity we're referring to.

2021-07-18 21:03 UTC, beckyjackson requested changes
Thanks! I just see two things:
* Remove `FILTER ( ?value != oboInOwl:ObsoleteClass )` at line 32; a deprecated class should never be equivalent or disjoint with `oboInOwl:ObsoleteClass`, only a subclass of it
* The anonymous expression check is duplicated. The first one should be removed, and just use the one where you're binding the string as `?entity`.

2021-07-19 07:57 UTC, matentzn commented
> The anonymous expression check is duplicated. The first one should be removed, and just use the one where you're binding the string as ?entity.

I wanted to increase the readability of cases where the axiom in question is a simple existential restriction; if you check the FILTER() expressions in both cases, you will find that one of these "duplicates" looks for cases were the entity is named, and then can be printed as part of the robot command.. Does this make sense?

2021-07-19 14:19 UTC, beckyjackson commented
OK - I don't think there should be duplicates within the report because that will conflate the number of issues. Both of these return anonymous expressions, and the first one just returns a (very unhelpful) blank node ID, which won't help the user locate the usage anyway, so I think it should be removed:
```
{
 VALUES ?property {
   owl:someValuesFrom
   owl:allValuesFrom
 }
 ?value a owl:Class ;
        owl:deprecated true .
 ?entity ?x ?rest .
 ?rest a owl:Restriction ;
       ?property ?value .
 FILTER(!isBlank(?entity))
}
UNION
{
 VALUES ?property {
   owl:someValuesFrom   
   owl:allValuesFrom
 }
 ?value a owl:Class ;
        owl:deprecated true .
 ?e ?x ?rest .
 ?rest a owl:Restriction ;
       ?property ?value .
 FILTER(isBlank(?e))
 BIND("anonymous expression" as ?entity)
}
```

2021-07-19 18:25 UTC, merged